### ISSUE TITLE
Tracker: Discord

### ISSUE THREAD

**Issue by gradiuscypher** [gradiuscypher/maximus#10]
Tracker implementation and documentation for the Discord service. Some things to consider:

- [ ] OPSEC considerations
- [ ] Setting up a proper discord account
- [ ] Storing discord events in elasticsearch
- [ ] How to store discord servers/users in the ORM
- [ ] Counter-detection considerations: fake activity, user message warning
- [ ] Containerized deployment
