### ISSUE TITLE
Tracker: Reddit

### ISSUE THREAD

**Issue by gradiuscypher** [gradiuscypher/maximus#11]
Tracker for Reddit. Some things to consider:
- [ ] OPSEC considerations
- [ ] How to set up Reddit tracking
- [ ] How to handle external links and multimedia
- [ ] How to store reddit messages in Elasticsearch
- [ ] How to apply reddit profiles to the ORM
- [ ] Tracking of entire subreddits instead of just users
