### ISSUE TITLE
Tracker: Twitch

### ISSUE THREAD

**Issue by gradiuscypher** [gradiuscypher/maximus#12]
- [ ] OPSEC considerations
- [ ] Twitch account configuration and setup
- [ ] How to store Twitch chat in Elasticsearch
- [ ] How to fit Twitch profiles into the ORM
- [ ] How to handle streams? Duplication of streams, save while livestreaming?
- [ ] How to index and leverage streams? Speech to text/captioning tools?
- [ ] Containerization of the service
