### ISSUE TITLE
Tracker: Github/Gitlab/Etc

### ISSUE THREAD

**Issue by gradiuscypher** [gradiuscypher/maximus#13]
Tracker implementation for Git-like repos. Things to consider:
- [ ] OPSEC considerations
- [ ] Code duplication
- [ ] User comment tracking
- [ ] User repo tracking
- [ ] User issue tracking
- [ ] User "star" tracking
- [ ] User "fork" tracking
